  export const styles = {
    container: {
      display: 'flex',
      minHeight: 'calc(100vh - 120px)',
      background: '#FBFAF6',
      padding: '2rem',
      maxWidth: '1200px',
      margin: '0 auto',
      gap: '2rem',
    },
    sidebar: {
      width: '280px',
      background: '#FBFAF6',
      borderRadius: '16px',
      border: '1px solid rgba(255, 255, 255, 0.8)',
      boxShadow: '0 4px 20px rgba(0, 0, 0, 0.06), 0 1px 4px rgba(0, 0, 0, 0.04)',
      padding: '1.5rem',
      height: 'fit-content',
      position: 'sticky' as const,
      top: '2rem',
    },
    header: {
      marginBottom: '2rem',
      paddingBottom: '1.5rem',
      borderBottom: '1px solid rgba(26, 19, 37, 0.1)',
    },
    title: {
      fontSize: '1.5rem',
      fontWeight: 600,
      color: '#161718',
      margin: '0 0 0.5rem 0',
    },
    subtitle: {
      fontSize: '0.95rem',
      color: '#666',
      fontWeight: 400,
      lineHeight: 1.5,
    },
    tabs: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '0.5rem',
    },
    tab: {
      display: 'flex',
      alignItems: 'center',
      gap: '1rem',
      padding: '1rem 1.25rem',
      background: 'transparent',
      color: '#666',
      border: 'none',
      borderRadius: '8px',
      cursor: 'pointer',
      fontWeight: 500,
      transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      textAlign: 'left' as const,
      width: '100%',
    },
    tabActive: {
      background: '#51258f',
      color: '#FBFAF6',
      boxShadow: '0 4px 12px rgba(26, 19, 37, 0.15)',
    },
    tabHover: {
      background: 'rgba(81, 37, 143, 0.1)',
      color: '#1a1325',
      transform: 'translateX(4px)',
    },
    content: {
      flex: 1,
      background: '#FBFAF6',
      padding: '2.5rem',
      borderRadius: '16px',
      border: '1px solid rgba(255, 255, 255, 0.8)',
      boxShadow: '0 4px 20px rgba(0, 0, 0, 0.06), 0 1px 4px rgba(0, 0, 0, 0.04)',
      backdropFilter: 'blur(10px)',
      minHeight: '100px',
    },
    section: {
      marginBottom: '2rem',
    },
    sectionTitle: {
      fontSize: '1.75rem',
      fontWeight: 600,
      color: '#161718',
      margin: '0 0 0.5rem 0',
    },
    sectionDescription: {
      color: '#666',
      fontSize: '1rem',
      margin: 0,
      lineHeight: 1.5,
    },
    formGrid: {
      display: 'grid',
      gap: '1.5rem',
    },
    formGridCompact: {
      display: 'grid',
      gap: '1.5rem',
      maxWidth: '500px',
    },
    infoCard: {
      padding: '1.5rem',
      background: 'rgba(26, 19, 37, 0.02)',
      borderRadius: '12px',
      border: '1px solid rgba(26, 19, 37, 0.1)',
    },
    infoCardTitle: {
      fontSize: '1rem',
      fontWeight: 600,
      color: '#1a1325',
      margin: '0 0 1rem 0',
    },
    infoGrid: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: '1rem',
    },
    field: {
      display: 'flex',
      flexDirection: 'column' as const,
      gap: '0.5rem',
    },
    fieldLabel: {
      fontSize: '0.9rem',
      fontWeight: 600,
      color: '#161718',
    },
    fieldInput: {
      padding: '0.875rem 1rem',
      border: '1.5px solid #e8e8e8',
      borderRadius: '8px',
      fontSize: '0.95rem',
      background: '#FBFAF6',
      transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      color: '#161718',
    },
    fieldInputDisabled: {
      padding: '0.875rem 1rem',
      border: '1.5px solid rgba(26, 19, 37, 0.1)',
      borderRadius: '8px',
      fontSize: '0.95rem',
      background: 'rgba(26, 19, 37, 0.05)',
      color: '#666',
      cursor: 'not-allowed',
    },
    fieldHint: {
      fontSize: '0.8rem',
      color: '#888',
      marginTop: '0.25rem',
    },
    actions: {
      display: 'flex',
      justifyContent: 'flex-end',
      marginTop: '2.5rem',
      paddingTop: '1.5rem',
      borderTop: '1px solid rgba(26, 19, 37, 0.1)',
    },
    button: {
      padding: '0.875rem 2rem',
      border: 'none',
      borderRadius: '8px',
      fontSize: '0.95rem',
      fontWeight: 600,
      cursor: 'pointer',
      transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
      position: 'relative' as const,
      overflow: 'hidden' as const,
    },
    buttonPrimary: {
      background: '#1a1325',
      color: '#FBFAF6',
      boxShadow: '0 2px 8px rgba(26, 19, 37, 0.2)',
    },
    buttonPrimaryHover: {
      background: '#24163a',
      transform: 'translateY(-1px)',
      boxShadow: '0 4px 16px rgba(26, 19, 37, 0.3)',
    },
    buttonDisabled: {
      background: '#ccc',
      color: '#666',
      cursor: 'not-allowed',
      transform: 'none',
      boxShadow: 'none',
    },
    availabilityCard: {
      padding: '3rem 2rem',
      textAlign: 'center' as const,
      background: 'rgba(26, 19, 37, 0.03)',
      borderRadius: '16px',
      border: '2px dashed rgba(26, 19, 37, 0.1)',
      backdropFilter: 'blur(10px)',
    },
    availabilityIcon: {
      fontSize: '3rem',
      marginBottom: '1.5rem',
      opacity: 0.8,
    },
    availabilityTitle: {
      fontSize: '1.5rem',
      fontWeight: 600,
      color: '#161718',
      margin: '0 0 1rem 0',
    },
    availabilityDescription: {
      color: '#666',
      marginBottom: '2rem',
      lineHeight: 1.6,
      maxWidth: '500px',
      marginLeft: 'auto',
      marginRight: 'auto',
    },
    infoHint: {
      padding: '1.25rem',
      background: 'rgba(26, 19, 37, 0.05)',
      border: '1px solid rgba(26, 19, 37, 0.1)',
      borderRadius: '12px',
      fontSize: '0.9rem',
      color: '#161718',
      textAlign: 'left' as const,
      maxWidth: '400px',
      margin: '0 auto',
    },
    infoList: {
      margin: '0.75rem 0 0 1rem',
      padding: 0,
      listStyle: 'none',
    },
    infoListItem: {
      marginBottom: '0.5rem',
      position: 'relative' as const,
      paddingLeft: '1rem',
    },
  };