// frontend/src/pages/Settings/type/SettingsType.tsx
export const styles = {
  container: {
    display: 'flex',
    minHeight: 'calc(100vh - 120px)',
    background: '#FBFAF6',
    padding: '2rem',
    maxWidth: '1200px',
    margin: '0 auto',
    gap: '2rem',
  },
  sidebar: {
    width: '280px',
    background: '#FBFAF6',
    borderRadius: '16px',
    border: '1px solid rgba(255, 255, 255, 0.8)',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.06), 0 1px 4px rgba(0, 0, 0, 0.04)',
    padding: '1.5rem',
    height: 'fit-content',
    position: 'sticky' as const,
    top: '2rem',
  },
  header: {
    marginBottom: '2rem',
    paddingBottom: '1.5rem',
    borderBottom: '1px solid rgba(26, 19, 37, 0.1)',
  },
  title: {
    fontSize: '1.5rem',
    fontWeight: 600,
    color: '#161718',
    margin: '0 0 0.5rem 0',
  },
  subtitle: {
    fontSize: '0.95rem',
    color: '#666',
    fontWeight: 400,
    lineHeight: 1.5,
  },
  tabs: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.5rem',
  },
  tab: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem 1.25rem',
    background: 'transparent',
    color: '#666',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 500,
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    textAlign: 'left' as const,
    width: '100%',
  },
  tabActive: {
    background: '#51258f',
    color: '#FBFAF6',
    boxShadow: '0 4px 12px rgba(26, 19, 37, 0.15)',
  },
  tabHover: {
    background: 'rgba(81, 37, 143, 0.1)',
    color: '#1a1325',
    transform: 'translateX(4px)',
  },
  content: {
    flex: 1,
    background: '#FBFAF6',
    padding: '2.5rem',
    borderRadius: '16px',
    border: '1px solid rgba(255, 255, 255, 0.8)',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.06), 0 1px 4px rgba(0, 0, 0, 0.04)',
    backdropFilter: 'blur(10px)',
    minHeight: '100px',
  },
  section: {
    marginBottom: '2rem',
  },
  sectionTitle: {
    fontSize: '1.75rem',
    fontWeight: 600,
    color: '#161718',
    margin: '0 0 0.5rem 0',
  },
  sectionDescription: {
    color: '#666',
    fontSize: '1rem',
    margin: 0,
    lineHeight: 1.5,
  },
  formGrid: {
    display: 'grid',
    gap: '1.5rem',
  },
  formGridCompact: {
    display: 'grid',
    gap: '1.5rem',
    maxWidth: '500px',
  },
  infoCard: {
    padding: '1.5rem',
    background: 'rgba(26, 19, 37, 0.02)',
    borderRadius: '12px',
    border: '1px solid rgba(26, 19, 37, 0.1)',
  },
  infoCardTitle: {
    fontSize: '1rem',
    fontWeight: 600,
    color: '#1a1325',
    margin: '0 0 1rem 0',
  },
  infoGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
  },
  field: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.5rem',
    width: '100%',
  },
  fieldLabel: {
    fontSize: '0.9rem',
    fontWeight: 600,
    color: '#161718',
    width: '100%',
  },
  fieldInputContainer: {
    position: 'relative' as const,
    width: '100%',
  },
  fieldInput: {
    padding: '0.875rem 1rem',
    border: '1.5px solid #e8e8e8',
    borderRadius: '8px',
    fontSize: '0.95rem',
    background: '#FBFAF6',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    color: '#161718',
    width: '100%',
    paddingRight: '40px',
    boxSizing: 'border-box' as const,
  },
  fieldInputWithIcon: {
    padding: '0.875rem 1rem',
    border: '1.5px solid #e8e8e8',
    borderRadius: '8px',
    fontSize: '0.95rem',
    background: '#FBFAF6',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    color: '#161718',
    width: '100%',
    paddingRight: '40px',
    boxSizing: 'border-box' as const,
  },
  fieldInputDisabled: {
    padding: '0.875rem 1rem',
    border: '1.5px solid rgba(26, 19, 37, 0.1)',
    borderRadius: '8px',
    fontSize: '0.95rem',
    background: 'rgba(26, 19, 37, 0.05)',
    color: '#666',
    cursor: 'not-allowed',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
  fieldHint: {
    fontSize: '0.8rem',
    color: '#888',
    marginTop: '0.25rem',
    width: '100%',
  },
  passwordToggleButton: {
    position: 'absolute' as const,
    right: '10px',
    top: '50%',
    transform: 'translateY(-50%)',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '5px',
    borderRadius: '4px',
    transition: 'background-color 0.2s',
    userSelect: 'none' as const,
    WebkitUserSelect: 'none' as const,
    touchAction: 'manipulation' as const,
  },
  actions: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: '2.5rem',
    paddingTop: '1.5rem',
    borderTop: '1px solid rgba(26, 19, 37, 0.1)',
  },
  button: {
    padding: '0.875rem 2rem',
    border: 'none',
    borderRadius: '8px',
    fontSize: '0.95rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'relative' as const,
    overflow: 'hidden' as const,
  },
  buttonPrimary: {
    background: '#1a1325',
    color: '#FBFAF6',
    boxShadow: '0 2px 8px rgba(26, 19, 37, 0.2)',
  },
  buttonPrimaryHover: {
    background: '#24163a',
    transform: 'translateY(-1px)',
    boxShadow: '0 4px 16px rgba(26, 19, 37, 0.3)',
  },
  buttonDisabled: {
    background: '#ccc',
    color: '#666',
    cursor: 'not-allowed',
    transform: 'none',
    boxShadow: 'none',
  },
  availabilityCard: {
    padding: '3rem 2rem',
    textAlign: 'center' as const,
    background: 'rgba(26, 19, 37, 0.03)',
    borderRadius: '16px',
    border: '2px dashed rgba(26, 19, 37, 0.1)',
    backdropFilter: 'blur(10px)',
  },
  availabilityIcon: {
    fontSize: '3rem',
    marginBottom: '1.5rem',
    opacity: 0.8,
  },
  availabilityTitle: {
    fontSize: '1.5rem',
    fontWeight: 600,
    color: '#161718',
    margin: '0 0 1rem 0',
  },
  availabilityDescription: {
    color: '#666',
    marginBottom: '2rem',
    lineHeight: 1.6,
    maxWidth: '500px',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  infoHint: {
    padding: '1.25rem',
    background: 'rgba(26, 19, 37, 0.05)',
    border: '1px solid rgba(26, 19, 37, 0.1)',
    borderRadius: '12px',
    fontSize: '0.9rem',
    color: '#161718',
    textAlign: 'left' as const,
    maxWidth: '400px',
    margin: '0 auto',
  },
  infoList: {
    margin: '0.75rem 0 0 1rem',
    padding: 0,
    listStyle: 'none',
  },
  infoListItem: {
    marginBottom: '0.5rem',
    position: 'relative' as const,
    paddingLeft: '1rem',
  },
  // Security tab styles
  providerList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1rem',
  },
  providerCard: {
    padding: '1.25rem',
    background: '#FBFAF6',
    borderRadius: '12px',
    border: '1px solid rgba(26, 19, 37, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    transition: 'all 0.2s ease',
  },
  providerCardHover: {
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.08)',
    borderColor: 'rgba(81, 37, 143, 0.3)',
  },
  providerInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    flex: 1,
  },
  providerIcon: {
    width: '40px',
    height: '40px',
    background: 'rgba(81, 37, 143, 0.1)',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.25rem',
  },
  providerDetails: {
    flex: 1,
  },
  providerName: {
    fontSize: '1rem',
    fontWeight: 600,
    color: '#161718',
    margin: 0,
  },
  providerIssuer: {
    fontSize: '0.85rem',
    color: '#666',
    margin: '0.25rem 0 0 0',
  },
  providerStatus: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.85rem',
    padding: '0.35rem 0.75rem',
    borderRadius: '20px',
  },
  providerStatusEnabled: {
    background: 'rgba(34, 197, 94, 0.1)',
    color: '#15803d',
  },
  providerStatusDisabled: {
    background: 'rgba(239, 68, 68, 0.1)',
    color: '#dc2626',
  },
  providerActions: {
    display: 'flex',
    gap: '0.5rem',
    marginLeft: '1rem',
  },
  iconButton: {
    padding: '0.5rem',
    background: 'transparent',
    border: '1px solid rgba(26, 19, 37, 0.1)',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1rem',
  },
  iconButtonHover: {
    background: 'rgba(81, 37, 143, 0.1)',
    borderColor: 'rgba(81, 37, 143, 0.3)',
  },
  iconButtonDanger: {
    color: '#dc2626',
  },
  iconButtonDangerHover: {
    background: 'rgba(239, 68, 68, 0.1)',
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  emptyState: {
    textAlign: 'center' as const,
    padding: '3rem 2rem',
    background: 'rgba(26, 19, 37, 0.02)',
    borderRadius: '12px',
    border: '2px dashed rgba(26, 19, 37, 0.1)',
  },
  emptyStateIcon: {
    fontSize: '3rem',
    marginBottom: '1rem',
    opacity: 0.6,
  },
  emptyStateText: {
    color: '#666',
    fontSize: '1rem',
    margin: '0 0 1.5rem 0',
  },
  modal: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    alignItems: 'flex-start', // Align to top
    justifyContent: 'center',
    zIndex: 1000,
    overflow: 'auto',
  },
  modalContent: {
    background: '#FBFAF6',
    borderRadius: '16px',
    width: '100%',
    alignItems: 'flex-start',
    overflow: 'hidden',
    boxShadow: '0 20px 40px rgba(0, 0, 0, 0.15)',
  },
  modalHeader: {
    padding: '1.5rem',
    borderBottom: '1px solid rgba(26, 19, 37, 0.1)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalTitle: {
    fontSize: '1.25rem',
    fontWeight: 600,
    color: '#161718',
    margin: 0,
  },
  modalClose: {
    background: 'none',
    border: 'none',
    fontSize: '1.5rem',
    cursor: 'pointer',
    color: '#666',
    padding: '0.25rem',
    lineHeight: 1,
  },
  modalBody: {
    padding: '1.5rem',
  },
  modalFooter: {
    padding: '1.5rem',
    borderTop: '1px solid rgba(26, 19, 37, 0.1)',
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '0.75rem',
  },
  buttonSecondary: {
    background: 'transparent',
    color: '#161718',
    border: '1px solid rgba(26, 19, 37, 0.2)',
  },
  buttonSecondaryHover: {
    background: 'rgba(26, 19, 37, 0.05)',
    borderColor: 'rgba(26, 19, 37, 0.3)',
  },
  buttonDanger: {
    background: '#dc2626',
    color: '#fff',
    boxShadow: '0 2px 8px rgba(220, 38, 38, 0.2)',
  },
  buttonDangerHover: {
    background: '#b91c1c',
    transform: 'translateY(-1px)',
    boxShadow: '0 4px 16px rgba(220, 38, 38, 0.3)',
  },
  buttonSuccess: {
    background: '#15803d',
    color: '#fff',
    boxShadow: '0 2px 8px rgba(21, 128, 61, 0.2)',
  },
  buttonSuccessHover: {
    background: '#166534',
    transform: 'translateY(-1px)',
    boxShadow: '0 4px 16px rgba(21, 128, 61, 0.3)',
  },
  testResult: {
    marginTop: '1rem',
    padding: '1rem',
    borderRadius: '8px',
    fontSize: '0.9rem',
  },
  testResultSuccess: {
    background: 'rgba(34, 197, 94, 0.1)',
    border: '1px solid rgba(34, 197, 94, 0.2)',
    color: '#15803d',
  },
  testResultError: {
    background: 'rgba(239, 68, 68, 0.1)',
    border: '1px solid rgba(239, 68, 68, 0.2)',
    color: '#dc2626',
  },
  fieldSelect: {
    padding: '0.875rem 1rem',
    border: '1.5px solid #e8e8e8',
    borderRadius: '8px',
    fontSize: '0.95rem',
    background: '#FBFAF6',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    color: '#161718',
    width: '100%',
    boxSizing: 'border-box' as const,
    cursor: 'pointer',
  },
  checkbox: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    cursor: 'pointer',
  },
  checkboxInput: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
    accentColor: '#51258f',
  },
  checkboxLabel: {
    fontSize: '0.95rem',
    color: '#161718',
    cursor: 'pointer',
  },
  divider: {
    height: '1px',
    background: 'rgba(26, 19, 37, 0.1)',
    margin: '1.5rem 0',
  },
  sectionSubtitle: {
    fontSize: '1rem',
    fontWeight: 600,
    color: '#161718',
    margin: '0 0 1rem 0',
  },
  headerActions: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
  },
};